//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.issue_book = new HashSet<issue_book>();
        }
    
        public int ID { get; set; }
        public string BOOK_NAME { get; set; }
        public string AUTHOR_NAME { get; set; }
        public string BOOK_CODE { get; set; }
        public Nullable<int> GENRE { get; set; }
        public string LANGUAGE { get; set; }
        public string PRICE { get; set; }
        public string SUBMITTED_BY { get; set; }
        public string AVAILABLE { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public Nullable<bool> IS_DELETE { get; set; }
        public Nullable<System.DateTime> ENT_DATE { get; set; }
    
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<issue_book> issue_book { get; set; }
    }
}
