//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class issue_book
    {
        public int ID { get; set; }
        public Nullable<int> BOOK_ID { get; set; }
        public Nullable<System.DateTime> ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> EXPIRY_DATE { get; set; }
        public string ISSUEBOOK { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public string DELAY_CHARGES { get; set; }
        public string FEES { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public Nullable<bool> IS_RETURN { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        public virtual book book { get; set; }
        public virtual registration registration { get; set; }
    }
}
