//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class library_m_Database1Entities1 : DbContext
    {
        public library_m_Database1Entities1()
            : base("name=library_m_Database1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<book> books { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<issue_book> issue_book { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<request_book> request_book { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
    }
}
