//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_role
    {
        public int ID { get; set; }
        public Nullable<int> USER_ID { get; set; }
        public string USER_ROLE1 { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }
    
        public virtual registration registration { get; set; }
    }
}
